<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\common.props"></Import>

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Platformus.Core.Api.Dto\Platformus.Core.Api.Dto.csproj" />
    <ProjectReference Include="..\Platformus.Website.Domain.Models\Platformus.Website.Domain.Models.csproj" />
  </ItemGroup>

</Project>
