<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\common.props"></Import>

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Magicalizer.Api.Dto.Abstractions" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Platformus.Core.Domain.Models\Platformus.Core.Domain.Models.csproj" />
  </ItemGroup>

</Project>
