//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platformus.Core.Admin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Core {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Core() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Platformus.Core.Admin.Resources.Core", typeof(Core).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurations.
        /// </summary>
        public static string Configurations {
            get {
                return ResourceManager.GetString("Configurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Configurations_Code {
            get {
                return ResourceManager.GetString("Configurations.Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create configuration.
        /// </summary>
        public static string Configurations_CreateConfiguration {
            get {
                return ResourceManager.GetString("Configurations.CreateConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a configuration.
        /// </summary>
        public static string Configurations_CreatingConfiguration {
            get {
                return ResourceManager.GetString("Configurations.CreatingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing a configuration.
        /// </summary>
        public static string Configurations_EditingConfiguration {
            get {
                return ResourceManager.GetString("Configurations.EditingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Configurations_Name {
            get {
                return ResourceManager.GetString("Configurations.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no value.
        /// </summary>
        public static string Configurations_NoValue {
            get {
                return ResourceManager.GetString("Configurations.NoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Configurations_Position {
            get {
                return ResourceManager.GetString("Configurations.Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials.
        /// </summary>
        public static string Credentials {
            get {
                return ResourceManager.GetString("Credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create credential.
        /// </summary>
        public static string Credentials_CreateCredential {
            get {
                return ResourceManager.GetString("Credentials.CreateCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a credential.
        /// </summary>
        public static string Credentials_CreatingCredential {
            get {
                return ResourceManager.GetString("Credentials.CreatingCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credential type.
        /// </summary>
        public static string Credentials_CredentialType {
            get {
                return ResourceManager.GetString("Credentials.CredentialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing a credential.
        /// </summary>
        public static string Credentials_EditingCredential {
            get {
                return ResourceManager.GetString("Credentials.EditingCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        public static string Credentials_Identifier {
            get {
                return ResourceManager.GetString("Credentials.Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Credentials_Password {
            get {
                return ResourceManager.GetString("Credentials.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email and password.
        /// </summary>
        public static string CredentialTypes_EmailAndPassword {
            get {
                return ResourceManager.GetString("CredentialTypes.EmailAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cultures.
        /// </summary>
        public static string Cultures {
            get {
                return ResourceManager.GetString("Cultures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-letter language code (ISO 639‑1).
        /// </summary>
        public static string Cultures_Code {
            get {
                return ResourceManager.GetString("Cultures.Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create culture.
        /// </summary>
        public static string Cultures_CreateCulture {
            get {
                return ResourceManager.GetString("Cultures.CreateCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a culture.
        /// </summary>
        public static string Cultures_CreatingCulture {
            get {
                return ResourceManager.GetString("Cultures.CreatingCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing a culture.
        /// </summary>
        public static string Cultures_EditingCulture {
            get {
                return ResourceManager.GetString("Cultures.EditingCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Cultures_Name {
            get {
                return ResourceManager.GetString("Cultures.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item?.
        /// </summary>
        public static string DeleteConfirmation_Message {
            get {
                return ResourceManager.GetString("DeleteConfirmation.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you confirm this item deletion?.
        /// </summary>
        public static string DeleteConfirmation_Title {
            get {
                return ResourceManager.GetString("DeleteConfirmation.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equals.
        /// </summary>
        public static string Equals {
            get {
                return ResourceManager.GetString("Equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not equals.
        /// </summary>
        public static string Not_equals {
            get {
                return ResourceManager.GetString("Not equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Roles_Code {
            get {
                return ResourceManager.GetString("Roles.Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create role.
        /// </summary>
        public static string Roles_CreateRole {
            get {
                return ResourceManager.GetString("Roles.CreateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a role.
        /// </summary>
        public static string Roles_CreatingRole {
            get {
                return ResourceManager.GetString("Roles.CreatingRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing a role.
        /// </summary>
        public static string Roles_EditingRole {
            get {
                return ResourceManager.GetString("Roles.EditingRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Roles_Name {
            get {
                return ResourceManager.GetString("Roles.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items.
        /// </summary>
        public static string Table_Items {
            get {
                return ResourceManager.GetString("Table.Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string Table_Of {
            get {
                return ResourceManager.GetString("Table.Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create user.
        /// </summary>
        public static string Users_CreateUser {
            get {
                return ResourceManager.GetString("Users.CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a user.
        /// </summary>
        public static string Users_CreatingUser {
            get {
                return ResourceManager.GetString("Users.CreatingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing a user.
        /// </summary>
        public static string Users_EditingUser {
            get {
                return ResourceManager.GetString("Users.EditingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string Users_FullName {
            get {
                return ResourceManager.GetString("Users.FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered.
        /// </summary>
        public static string Users_Registered {
            get {
                return ResourceManager.GetString("Users.Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Variables_Code {
            get {
                return ResourceManager.GetString("Variables.Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create variable.
        /// </summary>
        public static string Variables_CreateVariable {
            get {
                return ResourceManager.GetString("Variables.CreateVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a variable.
        /// </summary>
        public static string Variables_CreatingVariable {
            get {
                return ResourceManager.GetString("Variables.CreatingVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing a variable.
        /// </summary>
        public static string Variables_EditingVariable {
            get {
                return ResourceManager.GetString("Variables.EditingVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Variables_Name {
            get {
                return ResourceManager.GetString("Variables.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Variables_Value {
            get {
                return ResourceManager.GetString("Variables.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
