<Project Sdk="Microsoft.NET.Sdk.Razor">
  <Import Project="..\common.props"></Import>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
  
  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Platformus.Core.Admin\Platformus.Core.Admin.csproj" />
    <ProjectReference Include="..\Platformus.Website.Api.Dto\Platformus.Website.Api.Dto.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Website.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Website.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Website.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Website.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
