<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\common.props"></Import>

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Magicalizer.Domain.Models.Abstractions" Version="5.0.2" />
    <PackageReference Include="Magicalizer.Validators.Abstractions" Version="5.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Platformus.Core.Data.Entities\Platformus.Core.Data.Entities.csproj" />
  </ItemGroup>

</Project>
