<Project Sdk="Microsoft.NET.Sdk.Razor">
  <Import Project="..\common.props"></Import>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Blazor.Bootstrap" Version="3.3.1" />
    <PackageReference Include="Blazored.FluentValidation" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="9.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="9.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="9.0.1" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="9.0.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.4.0" />
    <PackageReference Include="TinyMCE.Blazor" Version="2.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Platformus.Core.Api.Dto\Platformus.Core.Api.Dto.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Core.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Core.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  
  <ItemGroup>
    <EmbeddedResource Update="Resources\Core.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Core.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
