//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platformus.Website.Admin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Website {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Website() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Platformus.Website.Admin.Resources.Website", typeof(Website).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes.
        /// </summary>
        public static string Classes {
            get {
                return ResourceManager.GetString("Classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create class.
        /// </summary>
        public static string Classes_CreateClass {
            get {
                return ResourceManager.GetString("Classes.CreateClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a class.
        /// </summary>
        public static string Classes_CreatingClass {
            get {
                return ResourceManager.GetString("Classes.CreatingClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# name.
        /// </summary>
        public static string Classes_CSharpName {
            get {
                return ResourceManager.GetString("Classes.CSharpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing a class.
        /// </summary>
        public static string Classes_EditingClass {
            get {
                return ResourceManager.GetString("Classes.EditingClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plural name.
        /// </summary>
        public static string Classes_PluralName {
            get {
                return ResourceManager.GetString("Classes.PluralName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singular name.
        /// </summary>
        public static string Classes_SingularName {
            get {
                return ResourceManager.GetString("Classes.SingularName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL segment.
        /// </summary>
        public static string Classes_UrlSegment {
            get {
                return ResourceManager.GetString("Classes.UrlSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create field.
        /// </summary>
        public static string Fields_CreateField {
            get {
                return ResourceManager.GetString("Fields.CreateField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a field.
        /// </summary>
        public static string Fields_CreatingField {
            get {
                return ResourceManager.GetString("Fields.CreatingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing a field.
        /// </summary>
        public static string Fields_EditingField {
            get {
                return ResourceManager.GetString("Fields.EditingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Fields_Name {
            get {
                return ResourceManager.GetString("Fields.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Fields_Type {
            get {
                return ResourceManager.GetString("Fields.Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop down list.
        /// </summary>
        public static string FieldTypes_DropDownList {
            get {
                return ResourceManager.GetString("FieldTypes.DropDownList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text area.
        /// </summary>
        public static string FieldTypes_TextArea {
            get {
                return ResourceManager.GetString("FieldTypes.TextArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text box.
        /// </summary>
        public static string FieldTypes_TextBox {
            get {
                return ResourceManager.GetString("FieldTypes.TextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forms.
        /// </summary>
        public static string Forms {
            get {
                return ResourceManager.GetString("Forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create form.
        /// </summary>
        public static string Forms_CreateForm {
            get {
                return ResourceManager.GetString("Forms.CreateForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a form.
        /// </summary>
        public static string Forms_CreatingForm {
            get {
                return ResourceManager.GetString("Forms.CreatingForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing a form.
        /// </summary>
        public static string Forms_EditingForm {
            get {
                return ResourceManager.GetString("Forms.EditingForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Forms_Name {
            get {
                return ResourceManager.GetString("Forms.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create member.
        /// </summary>
        public static string Members_CreateMember {
            get {
                return ResourceManager.GetString("Members.CreateMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a member.
        /// </summary>
        public static string Members_CreatingMember {
            get {
                return ResourceManager.GetString("Members.CreatingMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# name.
        /// </summary>
        public static string Members_CSharpName {
            get {
                return ResourceManager.GetString("Members.CSharpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing a member.
        /// </summary>
        public static string Members_EditingMember {
            get {
                return ResourceManager.GetString("Members.EditingMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localizable.
        /// </summary>
        public static string Members_Localizable {
            get {
                return ResourceManager.GetString("Members.Localizable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Members_Name {
            get {
                return ResourceManager.GetString("Members.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shown in list.
        /// </summary>
        public static string Members_ShownInList {
            get {
                return ResourceManager.GetString("Members.ShownInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Members_Type {
            get {
                return ResourceManager.GetString("Members.Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML.
        /// </summary>
        public static string MemberTypes_Html {
            get {
                return ResourceManager.GetString("MemberTypes.Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text box.
        /// </summary>
        public static string MemberTypes_TextBox {
            get {
                return ResourceManager.GetString("MemberTypes.TextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create menu item.
        /// </summary>
        public static string MenuItems_CreateMenuItem {
            get {
                return ResourceManager.GetString("MenuItems.CreateMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a menu item.
        /// </summary>
        public static string MenuItems_CreatingMenuItem {
            get {
                return ResourceManager.GetString("MenuItems.CreatingMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing a menu item.
        /// </summary>
        public static string MenuItems_EditingMenuItem {
            get {
                return ResourceManager.GetString("MenuItems.EditingMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string MenuItems_Name {
            get {
                return ResourceManager.GetString("MenuItems.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menus {
            get {
                return ResourceManager.GetString("Menus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create menu.
        /// </summary>
        public static string Menus_CreateMenu {
            get {
                return ResourceManager.GetString("Menus.CreateMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a menu.
        /// </summary>
        public static string Menus_CreatingMenu {
            get {
                return ResourceManager.GetString("Menus.CreatingMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing a menu.
        /// </summary>
        public static string Menus_EditingMenu {
            get {
                return ResourceManager.GetString("Menus.EditingMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Menus_Name {
            get {
                return ResourceManager.GetString("Menus.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects.
        /// </summary>
        public static string Objects {
            get {
                return ResourceManager.GetString("Objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create object.
        /// </summary>
        public static string Objects_CreateObject {
            get {
                return ResourceManager.GetString("Objects.CreateObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating an object.
        /// </summary>
        public static string Objects_CreatingObject {
            get {
                return ResourceManager.GetString("Objects.CreatingObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing an object.
        /// </summary>
        public static string Objects_EditingObject {
            get {
                return ResourceManager.GetString("Objects.EditingObject", resourceCulture);
            }
        }
    }
}
