<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\common.props"></Import>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Magicalizer" Version="5.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Platformus.Website.Domain.Models\Platformus.Website.Domain.Models.csproj" />
  </ItemGroup>

</Project>
